# Install nodejs
FROM node:6.11-alpine

RUN apk --update --no-cache add redis
RUN apk --update --no-cache add mongodb

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json .
COPY package-lock.json .

RUN npm install

# Bundle app source
COPY . .
COPY .env.docker .env

CMD [ "npm", "start" ]
