version: "2"
services:
  ambrogio:
    build: 
      context: .
      dockerfile: Dockerfile-ambrogio
    links:
      - uniopen
      - redis
  uniopen:
    build:
      context: .
      dockerfile: Dockerfile-uniopen
    ports:
      - "5000:5000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"