version: '2'

volumes:
  node:

services:
  uo2:
    build: .
    command: npm run dev
    restart: always
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - ./grabber:/uo2/grabber
      - node:/uo2/node_modules
    links:
      - redis
      - uniopen2-db
    depends_on:
      - redis
      - uniopen2-db

  uniopen2-db:
    image: mongo:3.6
    restart: always
    volumes:
      - './data:/data/db'
    expose:
      - '27017'
    command: mongod --smallfiles --logpath=/dev/null

  redis:
    image: redis:4.0-alpine
    restart: always
    expose:
      - '6379'
    command: redis-server
